### ISSUE TITLE
Frequent dependabot alerts: Best way to handle?

### ISSUE THREAD

**Issue by hartwork** [gentoo/recruiting.gentoo.org#98]
Hi!

I keep getting mail about [dependabot alerts](https://github.com/gentoo/recruiting.gentoo.org/network/alerts) with regard to this repository: ignoring the repository doesn't help. I cannot silence these mails altogether to no go blind to alerts from other repositories. I cannot silence the related issues without prior agreement either, because it would silence them for everyone. 

The latest commit in here is of 2015. Is it time to archive this repository? Does someone want to adress the core of the issues by doing dependency bumps? Other ideas?

Thanks and best, Sebastian

**Comment by hartwork** [comment]
Another mail today. Any thoughts?

**Comment by hartwork** [comment]
Another mail yesterday. Any thoughts? I will move forward with mass-dismissing the warnings when the next mail arrives (in ~5 days) and I haven't heard back from anyone here.

**Comment by Zlogene** [comment]
@hartwork recruiting webapp has been abandoned for ages and I do not expect it to come to life ever again (at least in the state it is in now).

**Comment by hartwork** [comment]
Thanks for your feedback. I have run action `Dismiss all: Vulnerable code is not actually used at all` now to address the issue. Closing as fixed.

**Comment by hartwork** [comment]
For the record, I triggered `Dismiss all: Vulnerable code is not actually used at all` again today.

**Comment by hartwork** [comment]
> For the record, I triggered `Dismiss all: Vulnerable code is not actually used at all` again today.

One more today.
